module.exports = {
  // USER MANAGEMENT
  CREATE_USER: "CREATE_USER",
  EDIT_USER: "EDIT_USER",
  DELETE_USER: "DELETE_USER",

  // DEVICE MANAGEMENT
  CREATE_DEVICE: "CREATE_DEVICE",
  EDIT_DEVICE: "EDIT_DEVICE",
  DELETE_DEVICE: "DELETE_DEVICE",
  RENEW_DEVICE: "RENEW_DEVICE",

  // DEVICE LEVEL
  EDIT_SPEED: "EDIT_SPEED",
  EDIT_FUEL: "EDIT_FUEL",
  EDIT_OIL: "EDIT_OIL",
  EDIT_CALL_NUMBER: "EDIT_CALL_NUMBER",
  EDIT_TRACKER_SIM: "EDIT_TRACKER_SIM",

  // GEOFENCE
  GEOFENCE_VIEW: "GEOFENCE_VIEW",
  GEOFENCE_CREATE: "GEOFENCE_CREATE",
  GEOFENCE_EDIT: "GEOFENCE_EDIT",
  GEOFENCE_DELETE: "GEOFENCE_DELETE",

  // COMMANDS
  SEND_COMMAND: "SEND_COMMAND",
  ENGINE_CONTROL: "ENGINE_CONTROL",

  // OPTIONAL
  VIEW_DEVICE: "VIEW_DEVICE",
  ASSIGN_DEVICE: "ASSIGN_DEVICE",
  MANAGE_DEVICE_PERMISSIONS: "MANAGE_DEVICE_PERMISSIONS",
  MARK_ALERTS: "MARK_ALERTS",
  CLEAR_ALERTS: "CLEAR_ALERTS",
  VIEW_USER: "VIEW_USER",
  VIEW_DASHBOARD: "VIEW_DASHBOARD"
};