module.exports = {
  VIEW_DEVICE: "VIEW_DEVICE",
  SEND_COMMAND: "SEND_COMMAND",
  EDIT_DEVICE: "EDIT_DEVICE",
  EDIT_SPEED: "EDIT_SPEED",
  EDIT_FUEL: "EDIT_FUEL",
  GEOFENCE_VIEW: "GEOFENCE_VIEW",
  GEOFENCE_CREATE: "GEOFENCE_CREATE",
  GEOFENCE_EDIT: "GEOFENCE_EDIT",
  GEOFENCE_DELETE: "GEOFENCE_DELETE"
};